// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1vI8yyPR-d9MYvrliuYHqVpucU9PB0mo',
    appId: '1:851102593535:web:02fba3054cf3bf95ac37ca',
    messagingSenderId: '851102593535',
    projectId: 'appmobile-2bbcb',
    authDomain: 'appmobile-2bbcb.firebaseapp.com',
    storageBucket: 'appmobile-2bbcb.firebasestorage.app',
    measurementId: 'G-9SZR9YWVTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtQPPoImQGmuJcEBJObuKqY-cdupACUE',
    appId: '1:851102593535:android:2535ed34dc96c19eac37ca',
    messagingSenderId: '851102593535',
    projectId: 'appmobile-2bbcb',
    storageBucket: 'appmobile-2bbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmf9njw2GL9qzy7VcBu3F51xXT1yajFw',
    appId: '1:851102593535:ios:c84ed1d72d02d425ac37ca',
    messagingSenderId: '851102593535',
    projectId: 'appmobile-2bbcb',
    storageBucket: 'appmobile-2bbcb.firebasestorage.app',
    iosBundleId: 'com.example.teladelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmf9njw2GL9qzy7VcBu3F51xXT1yajFw',
    appId: '1:851102593535:ios:c84ed1d72d02d425ac37ca',
    messagingSenderId: '851102593535',
    projectId: 'appmobile-2bbcb',
    storageBucket: 'appmobile-2bbcb.firebasestorage.app',
    iosBundleId: 'com.example.teladelogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1vI8yyPR-d9MYvrliuYHqVpucU9PB0mo',
    appId: '1:851102593535:web:2929a82128267addac37ca',
    messagingSenderId: '851102593535',
    projectId: 'appmobile-2bbcb',
    authDomain: 'appmobile-2bbcb.firebaseapp.com',
    storageBucket: 'appmobile-2bbcb.firebasestorage.app',
    measurementId: 'G-YKTT0LHML9',
  );

}